[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "melody-web"
version = "0.1.2"
description = "A Python web framework to quickly build web apps"
requires-python = ">=3.10"

dependencies = [
    "uvicorn",
    "werkzeug",
    "beautifulsoup4",
    "Jinja2",
    "python-dotenv",
    "peewee",
]

[project.scripts]
melody = "melody.cli:main"