[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "melody"
version = "0.1.0"
description = "A Python webframework to quickly build web apps"

dependencies = [
    "uvicorn",
    "werkzeug",
    "beautifulsoup4",
    "Jinja2",
"beautifulsoup4",
"dotenv"
]

[project.scripts]
melody = "melody.cli:main"